"""LEAN export/import handoff helpers."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

from config import DATA_DIR, LEAN_EXPORT_ENABLED
from data.cache import Cache, get_latest_scan
from data.strategy_registry import StrategyRegistry
from models.schemas import Bucket, LeanExportRequest
from services.allocation_recommender import get_allocation_recommendation
from services.portfolio_optimizer import optimize_portfolio
from services.qlib_integration import get_latest_alpha

LEAN_DIR = Path(DATA_DIR) / "lean_exports"
LEAN_DIR.mkdir(parents=True, exist_ok=True)


def _utc_iso() -> str:
    return datetime.now(timezone.utc).replace(tzinfo=None).isoformat()


def _resolve_symbols(bucket: Bucket, requested: list[str]) -> list[str]:
    symbols = [s.strip().upper() for s in requested if s and s.strip()]
    symbols = list(dict.fromkeys(symbols))
    if symbols:
        return symbols

    latest = get_latest_scan(bucket.value) or {}
    results = latest.get("results") or []
    scan_symbols = [str(r.get("symbol", "")).upper() for r in results if r.get("symbol")]
    return list(dict.fromkeys(scan_symbols))[:20]


def _filter_alpha(alpha_payload: dict, symbols: list[str]) -> list[dict]:
    lookup = {s.upper() for s in symbols}
    return [row for row in alpha_payload.get("items", []) if str(row.get("symbol", "")).upper() in lookup]


def build_lean_export(request: LeanExportRequest) -> tuple[str, str, dict]:
    symbols = _resolve_symbols(request.bucket, request.symbols)
    if len(symbols) < 2:
        raise ValueError("Need at least 2 symbols for LEAN export")

    strategy = StrategyRegistry().get_active(request.bucket.value)
    allocation = get_allocation_recommendation(request.bucket, symbols)
    try:
        optimized = optimize_portfolio(
            symbols,
            objective=request.objective,
            max_weight=request.max_weight,
            cash_buffer=request.cash_buffer,
            lookback_period=request.lookback_period,
        )
        optimized_weights = optimized.weights
        optimizer_notes = optimized.notes or []
    except Exception as exc:
        optimized_weights = {}
        optimizer_notes = [f"Optimizer unavailable: {exc}"]

    weights = allocation.get("target_weights") or []
    if not weights and optimized_weights:
        weights = [{"symbol": s, "target_weight": float(w)} for s, w in optimized_weights.items()]

    alpha_payload = get_latest_alpha(request.bucket) if request.include_alpha else {"items": []}
    alpha_items = _filter_alpha(alpha_payload, symbols)

    scan_payload = get_latest_scan(request.bucket.value) if request.include_latest_scan else None
    scan_results = []
    if scan_payload:
        keep = {s.upper() for s in symbols}
        scan_results = [r for r in scan_payload.get("results", []) if str(r.get("symbol", "")).upper() in keep]

    export_id = f"lean_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{uuid4().hex[:8]}"
    created_at = _utc_iso()
    payload = {
        "export_id": export_id,
        "created_at": created_at,
        "enabled": bool(LEAN_EXPORT_ENABLED),
        "bucket": request.bucket.value,
        "strategy_version": strategy.version_id,
        "symbols": symbols,
        "config": {
            "rebalance": request.rebalance,
            "objective": request.objective,
            "lookback_period": request.lookback_period,
            "max_weight": request.max_weight,
            "cash_buffer": request.cash_buffer,
            "include_alpha": request.include_alpha,
            "include_latest_scan": request.include_latest_scan,
        },
        "target_weights": weights,
        "optimizer_weights": optimized_weights,
        "alpha_signals": alpha_items,
        "latest_scan": {
            "completed_at": (scan_payload or {}).get("completed_at"),
            "strategy_version": (scan_payload or {}).get("strategy_version"),
            "results": scan_results,
        },
        "notes": [request.notes] if request.notes else [],
        "meta_notes": optimizer_notes
        + [
            "LEAN handoff export generated by Stock Picker.",
            "Use this payload as input for LEAN algorithm parameterization/import.",
        ],
    }

    safe_name = (request.export_name or export_id).strip().replace(" ", "_")
    file_path = LEAN_DIR / f"{safe_name}.json"
    with file_path.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)

    cache = Cache()
    cache.set(f"lean:export:{export_id}", {"path": str(file_path), "created_at": created_at}, 86400 * 30)
    return export_id, str(file_path), payload


def load_lean_export(export_id: str) -> dict:
    cache = Cache()
    meta = cache.get(f"lean:export:{export_id}") or {}
    path = meta.get("path")
    if path:
        p = Path(path)
        if p.exists():
            with p.open("r", encoding="utf-8") as fh:
                return json.load(fh)

    candidates = list(LEAN_DIR.glob(f"*{export_id}*.json"))
    if not candidates:
        raise FileNotFoundError(f"LEAN export not found: {export_id}")
    with candidates[0].open("r", encoding="utf-8") as fh:
        return json.load(fh)


def save_lean_summary(export_id: str, status: str, metrics: dict, notes: str = "") -> str:
    created_at = _utc_iso()
    payload = {
        "export_id": export_id,
        "status": status,
        "created_at": created_at,
        "metrics": metrics,
        "notes": notes,
    }
    summary_path = LEAN_DIR / f"{export_id}.summary.json"
    with summary_path.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)

    cache = Cache()
    cache.set(
        f"lean:summary:{export_id}",
        {"path": str(summary_path), "status": status, "created_at": created_at},
        86400 * 30,
    )
    return str(summary_path)

