"""Audit scalability limits for Factor Discovery staging."""
from __future__ import annotations

MAXIMUM_SAMPLE_SYMBOLS = 50
MAXIMUM_FLAGGED_EXAMPLES_PER_CATEGORY = 20
MAXIMUM_JUMP_ROWS_PER_SYMBOL = 500
MAXIMUM_QUOTE_ALIGNMENT_SAMPLE = 5000
MAXIMUM_MEMBERSHIP_DATE_SAMPLES = 20
QUERY_TIMEOUT_SECONDS = 30
